name: Build and push images to GitHub Container Registry

on: workflow_dispatch

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: USERNAME
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build wivet image
        run: docker build --tag ghcr.io/neuralegion/wivet:latest .

      - name: Push wivet image
        run: docker push ghcr.io/neuralegion/wivet:latest

